srvs:
  - service_name: A
    count_pods: 3
    handlers:
      - handler: 1
        time: 10
        way: [3, 4]
      - handler: 2
        time: 10
  
  - service_name: B
    count_pods: 3
    handlers:
      - handler: 3
        time: 10
      - handler: 4
        time: 10
  