srvs:
  - service_name: A
    pods_weight: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
    count_pods: 12
    max_length_queue_task: 100
    handlers:
      - handler: 1
        probability: 0.25
        time: 50
        way: [3, 4]
      - handler: 2
        probability: 0.25
        time: 50
  
  - service_name: B
    pods_weight: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
    weight: 1
    count_pods: 12
    max_length_queue_task: 100
    handlers:
      - handler: 3
        probability: 0.25
        time: 50
      - handler: 4
        probability: 0.25
        time: 50
generator:
  interval: 200
  count_in_iteration: 5
  